codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree
  show_carryforward_flags: false
coverage:
  precision: 2
  range: 70..1000
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project:
      default:
        target: 90%
github_checks:
  annotations: true
