name: Merge
on:
  push:
    branches: [main]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name bot
          git config --global user.email github-actions@github.com

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Add change to release
        uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Write package version
        run: |
          node > script <<EOF
            const fs = require("fs");
            const data = require("./package.json");

            data.version = "${{ steps.release.outputs.name }}".slice(1, "${{ steps.release.outputs.name }}".length);
            
            fs.writeFile("./package.json", JSON.stringify(data, null, 2), console.error);
          EOF

      - name: Push versions
        run: |
          git add ./package.json
          git commit -m "Bump version - ${{ steps.release.outputs.name }} build ${{ github.run_number }} [skip ci]" || echo "No changes"
          git push
