name: Verify
on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build lib
        run: yarn workspace e-prim build

      - name: Verify bundle size
        run: yarn workspace e-prim bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

      - name: Build example
        run: yarn workspace example build

      - name: Build docs
        run: yarn workspace docs build

      - name: Test
        run: yarn workspace e-prim test --coverage-reports=json-summary

      - name: Upload coverage results
        uses: codecov/codecov-action@v3
        with:
          files: ./lib/coverage/coverage-summary.json
