name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Configure Git
        run: |
          git config --global user.name bot
          git config --global user.email github-actions@github.com

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn workspace e-prim build

      - name: Release
        working-directory: lib
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish docs
        working-directory: docs
        env:
          GIT_USER: dstoyanoff
          GIT_PASS: ${{ secrets.ACTIONS_TOKEN }}
        run: yarn workspace docs deploy

      - name: Publish release
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });    

            const draftRelease = releases.data.find(r => r.draft);

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: draftRelease.id,
              draft: false
            });
