name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name bot
          git config user.email github-actions@github.com

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish docs
        working-directory: docs
        env:
          USE_SSH: true
          GUT_PASS: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          yarn
          yarn build
          yarn deploy

      - name: Publish tags
        run: git push --tags
